FROM php:8.2-apache
WORKDIR /public
COPY . .
RUN apt-get update && apt-get install -y \
    unzip \
    && docker-php-ext-install pdo pdo_mysql
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install --no-dev --optimize-autoloader
RUN chown -R www-data:www-data /public/storage /public/bootstrap/cache
EXPOSE 80
CMD ["apache2-foreground"]
